export enum MathErrorCode {
  DivisionByZero = "MATH_DIVISION_BY_ZERO",
  FormatRawFailed = "MATH_FORMAT_RAW_FAILED",
  InvalidAddend = "MATH_INVALID_ADDEND",
  InvalidCompareTo = "MATH_INVALID_COMPARE_TO",
  InvalidDecimalPlaces = "MATH_INVALID_DECIMAL_PLACES",
  InvalidDivisor = "MATH_INVALID_DIVISOR",
  InvalidFormatUnit = "MATH_INVALID_FORMAT_UNIT",
  InvalidGroupingSize = "MATH_INVALID_GROUPING_SIZE",
  InvalidMultiplier = "MATH_INVALID_MULTIPLIER",
  InvalidNano = "MATH_INVALID_NANO",
  InvalidRaw = "MATH_INVALID_RAW",
  InvalidRawResult = "MATH_INVALID_RAW_RESULT",
  InvalidSubtrahend = "MATH_INVALID_SUBTRAHEND",
  NegativeAddend = "MATH_NEGATIVE_ADDEND",
  NegativeRaw = "MATH_NEGATIVE_RAW",
  NegativeResult = "MATH_NEGATIVE_RESULT",
  NegativeSubtrahend = "MATH_NEGATIVE_SUBTRAHEND",
  NonIntegerResult = "MATH_NON_INTEGER_RESULT",
  ResultOutOfRange = "MATH_RESULT_OUT_OF_RANGE",
  Unexpected = "MATH_UNEXPECTED_ERROR",
}
