export enum BlockErrorCode {
  BalanceOutOfRange = "BLOCK_BALANCE_OUT_OF_RANGE",
  DeriveAccountFromBlockLinkFailed = "BLOCK_DERIVE_ACCOUNT_FROM_BLOCK_LINK_FAILED",
  DeriveAccountFromFrontierLinkFailed = "BLOCK_DERIVE_ACCOUNT_FROM_FRONTIER_LINK_FAILED",
  DeriveAccountFromSendLinkFailed = "BLOCK_DERIVE_ACCOUNT_FROM_SEND_LINK_FAILED",
  DerivePublicKeyFromDestinationFailed = "BLOCK_DERIVE_PUBLIC_KEY_FROM_DESTINATION_FAILED",
  FrontierLinkMismatch = "BLOCK_FRONTIER_LINK_MISMATCH",
  HashFrontierBlockFailed = "BLOCK_HASH_FRONTIER_BLOCK_FAILED",
  HashSendBlockFailed = "BLOCK_HASH_SEND_BLOCK_FAILED",
  InsufficientBalance = "BLOCK_INSUFFICIENT_BALANCE",
  InvalidAmount = "BLOCK_INVALID_AMOUNT",
  InvalidCreatedBlock = "BLOCK_INVALID_CREATED_BLOCK",
  InvalidDestination = "BLOCK_INVALID_DESTINATION",
  InvalidFrontierBlock = "BLOCK_INVALID_FRONTIER_BLOCK",
  InvalidRepresentative = "BLOCK_INVALID_REPRESENTATIVE",
  InvalidSendBlock = "BLOCK_INVALID_SEND_BLOCK",
  NegativeAmount = "BLOCK_NEGATIVE_AMOUNT",
  SendDestinationMismatch = "BLOCK_SEND_DESTINATION_MISMATCH",
  SendLinkMismatch = "BLOCK_SEND_LINK_MISMATCH",
  SignBlockFailed = "BLOCK_SIGN_BLOCK_FAILED",
  Unexpected = "BLOCK_UNEXPECTED_ERROR",
}
